- build.gradle
- src/main/java/roomescape/HomeController.java
- src/main/java/roomescape/_core/errors/Exception/Exception400.java
- src/main/java/roomescape/_core/errors/GlobalExceptionHandler.java
- src/main/java/roomescape/reservation/Reservation.java
- src/main/java/roomescape/reservation/ReservationController.java
- src/main/java/roomescape/reservation/ReservationRepository.java
- src/main/java/roomescape/reservation/ReservationResponse.java
- src/main/java/roomescape/reservation/ReservationService.java
- src/main/java/roomescape/reservation/dto/ReservationRequest.java
- src/main/java/roomescape/reservation/dto/ReservationResponse.java
- src/test/java/roomescape/MissionStepTest.java
1주차 미션 제출합니다~!
시간은 일주일이나 주어졌지만, 좀 급하게 하는 바람에...ㅎ 이것저것 확인도 못하고 빠르게 제출하네요ㅠㅠ
정말 어제오늘 틈틈이 하느라 코드가 좀 정신없지만, 잘 부탁드립니당!
시간 나면 다시 코드 고쳐보겠습니다!
> [Spring MVC] 미나(이지민) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/controller/PageController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/dto/Reservation.java
- src/main/java/roomescape/exception/ExceptionsHandler.java
- src/main/java/roomescape/exception/IllegalReservationException.java
- src/main/java/roomescape/exception/NotFoundReservationException.java
- src/test/java/roomescape/MissionStepTest.java
> 다음 과제는 제출 시간 엄수!! 하겠습니다! 부족한 만큼 남들보다 빨리 시작해서 시간 엄수하겠습니다.
- 이번에 미션 1~4 차근차근 적용해보았습니다.
- `dto`랑 `entity`를 따로 두어야하는지 궁금합니다. 다른 블로그 글을 보니, dto를 따로 두고 id를 따로 빼서 entity를 생성할 때 넣어주는 것을 보았습니다. 덕분에 엄청 삽질하다가 굳이 왜 그렇게 하는지 아직까지 조금 이해하기 어려워서 적용은 따로 못해보고 구현하는데만 집중했습니다.
- `exception`처리할 때 `custom exception`으로 처리해도 좋다고 하셔서 처음으로 해봤는데 이렇게 하는게 맞는지 잘 모르겠습니다.
- `controller`에 `api`디렉터리에 있어야 할 것을 몽땅 집어넣은 느낌이 납니다. **페이지를 매핑하는 것**과  **CRUD기능을 구현하는 것**들이 함께 `controller`에 속하는지 궁금합니다.
- 마니 부족한 코드지만 부족한 부분들 모두 날카롭게 지적 환영합니다!
- 스프링으로 백엔드 해본적이 영한킴 강의들은 것 빼고 처음이라 조금 낯설었습니다.. 
- 이번에 미션 2에서 처음 막혀서 어제 그래도 한 만큼 PR올릴려고 했는데 실수로 포크를 안하고 해서 origin/stopmin에서 stopmin03레포지토리로 옮기려다 head상태에서 branch를 옮겨버리는 바람에 수정내역이 모두 날아가버려서 덕분에 어제 저녁 3시부터 다시했답니닷..
- 덕분에 정말 많이 배워갑니당.. 중간에 개발했던 것들이 날아가버려 재미를 잃었지만 뒤에부터는 하다보니 기분이 좋아져서 재밌었습니다.
**모두 …
> [Spring MVC] 버디(정지민) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/ExceptionCollection.java
- src/main/java/roomescape/HomeController.java
- src/main/java/roomescape/Reservation.java
- src/main/java/roomescape/ReservationController.java
- src/main/java/roomescape/RoomescapeApplication.java
- src/test/java/roomescape/MissionStepTest.java
브랜치를 파지 않고 main에서 작업하는 바람에 다시 제출합니다!
* 예외처리와 관련된 폴더 구조를 어떻게 하면 좋을 지 잘 모르겠습니다.
추천해주세요!
* 예약 생성하는 API에서 예외처리 할 때, `reservation.getTime() == null` 로 예외 상황 확인하고 싶었는데요.
UI에 나온 time 포맷을 맞추기 위해, formatter 를 사용했습니다.
하지만 formatter를 사용하니, time에 `null`이 들어갈 경우 format하는 과정에서 에러가 발생합니다.
그래서 API를 호출하면 500으로 돌려줍니다....
이를 방지하기 위해 Reservation class에 getTimeNotFormatted()함수를 한 개 더 생성했는데 깔끔하지 않은 것 같습니다.
혹시 좋은 방법있으면 알려주세요.
> [Spring MVC] 챠휴(이다은) 미션 제출합니다

- build.gradle
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/RoomescapeController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/exception/GlobalException.java
- src/main/java/roomescape/exception/NotFoundReservationException.java
- src/main/java/roomescape/repository/Reservation.java
- src/main/java/roomescape/utils/ErrorMessage.java
- src/main/java/roomescape/validation/ReservationValidation.java
- src/main/resources/application.properties
- src/test/java/roomescape/MissionStepTest.java
ㅎㅎ... 급하게 했습니다ㅠㅠ
리뷰 잘부탁드립니다~!! 
`@valid`를 사용해서 `@NotBlank`로 유효성 처리를 해보려고 했는데 그렇게 하니 커스텀 에러를 어떻게 만들어야 할지 모르겠어서...🤔  
그냥 얌전히 하던대로 유효성 검사 했습니다,,,
> [Spring MVC] 팜(임연후) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/Reservation.java
- src/main/java/roomescape/ReservationController.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
* 예약 삭제 api을 실행할 때, 없는 id를 보내면 `405 Method Not Allowed`로 반환됩니다.
반환 코드가 400이 아니라서 불편한 마음이 있는데, 이대로 괜찮은 건지 궁금합니다.
> [Spring JDBC] 챠휴(이다은) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/domain/reservation/controller/ReservationController.java
- src/main/java/roomescape/domain/reservation/dto/request/CreateReservationRequest.java
- src/main/java/roomescape/domain/reservation/entity/Customer.java
- src/main/java/roomescape/domain/reservation/entity/Reservation.java
- src/main/java/roomescape/domain/reservation/repository/ReservationRepository.java
- src/main/java/roomescape/domain/reservation/repository/ReservationRepositoryImpl.java
- src/main/java/roomescape/domain/reservation/repository/ReservationRepositoryJdbc.java
- src/main/java/roomescape/domain/reservation/service/ReservationService.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
안녕하세용. JDBC 미션 제출 합니다.
다들 감기랑 몸살 조심하세요..!!
> [Spring JDBC] 짱구(이수빈) 미션 제출합니다.

- .gitignore
- env
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/customer/controller/CustomerController.java
- src/main/java/roomescape/customer/domain/Customer.java
- src/main/java/roomescape/reservation/domain/Reservation.java
- src/main/java/roomescape/reservation/service/ReservationService.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
- src/test/java/roomescape/RoomescapeControllerTest.java
제가 지난주에 List 및 AtomicLong를 사용하지 않고 h2로 바로 사용해버려서... 😢 이번 commit에는 들어가지 않았습니다..! 
- List 및 AtomicLong는 나중에 복습하면서 따라해보겠습니담
코드 리뷰 잘 부탁드립니다! 😄 
- Customer 생성 
- Customer Controller 생성 
- reservation sql schema 생성 
- step 5-7 test code 작성  
- h2 관련 yml 수정 
- 요즘 test 코드 작성에 관심이 많아서, test 코드를 더 보기 좋고 사용하기 좋은 방법으로 작성해보고 싶습니다! 이 부분에 대해서 피드백 원합니담(지난주차 보름님 피드백은 아직 반영못했습니다...!) 
- 제가 생성한 폴더 구조에 대해서 어떤지 궁금합니다!
> [Spring JDBC] 쏘(박소현) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/repository/ReservationRepository.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest567.java
헤헤... 늦어서 죄송합니다
사실 일찍 끝내놨는데 마지막에 service하고 repository 분리하는 간단한 리팩토링 하는게 귀찮아서 손놓고 있다가 이제 했습니다^^;
JPA만 공부해봐서 JDBC 템플릿은 처음 사용해봤는데 그래도 나음 JPA 인강 들으면서 배운 거 가능한 한 적용해봤습니다... (사실 적용할수 있는 게 거의 없었지만,,) 잘부탁드립니다~
> [Spring JDBC] 팜(임연후) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/Room.java
- src/main/java/roomescape/RoomController.java
- src/main/java/roomescape/RoomRepository.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
- Repository 계층을 HashMap이 아닌 H2-JDBC를 이용하도록 변경
- 이와 관련된 테스트 추가
- jdbcTemplate 활용법
- JDBC 관련 모르는 부분이 많다는 것.
- 순수 JDBC활용하여 로직 처리
- 커넥션 풀
- `SimpleJdbcInsert`
- `org.springframework.jdbc.core.simple` 에 위치한 객체이다.
- JDBC 삽입 관련 연산을 간단하게 지원한다.
- hash map을 통한 삽입
- 쉽게 키를 획득
- `core.simple`은  `StoredProcedure`을 호출할 수 있는  `SimpleJdbcCall` 을 제공하기도 한다.
- `StoredProcedure` 은  DBMS 상에서 로직을 실행하는 것.
- 장점
- 네트워크 비용 감소.
- 다양한 종류의 서버에서 같은 로직 실행 가능.
- 단점
- 유지보수 비용 증가.
- DBMS가 단일 실패점이 됨.
- 유연한 코드 작성, 디버깅이 어려움.
- `Number Object`: Java의 추상 객체
- Integer, Long, Short, Byte 모두 이를 상속함.
- `intValue()`, `longValue()` 등의 타입 캐스팅을 메서드로 제공함.
- `DataSource`
- 기존, 수동으로 연결했던 것과 달리 파일 기반으로 DB 커넥션을 맺어줌.
- 커넥션 풀 반납의 역할도 맡음.
- `EmptyResultDataAccessException`
- 데이터 액세스 결과 0개의 결과가 있을 때 반환되는 런타임 에러
- 개발자 의도에 따라 그대로 throw할 수도, …
> [Spring JDBC 2주차] 박한수 미션 제출합니다.

- .gitignore
- build.gradle
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/java/roomescape/query/ReservationQuery.java
- src/main/java/roomescape/repository/ReservationRepository.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
H2 DB를 연결해 예약을 조회, 추가, 삭제하도록 구현하였습니다.
- RowMapper와 JdbcTemplate, SimpleJdbcInsert이 무엇인지와 사용 방법
- H2 데이터베이스 연결 방법
> [Spring JDBC 2주차] 박다희 미션 제출합니다. 

- src/main/java/roomescape/reservation/domain/Reservation.java
- src/main/java/roomescape/reservation/dto/request/ReservationRequest.java
- src/main/java/roomescape/reservation/dto/response/ReservationResponse.java
- src/main/java/roomescape/time/controller/TimeController.java
- src/main/java/roomescape/time/domain/Time.java
- src/main/java/roomescape/time/dto/request/TimeRequest.java
- src/main/java/roomescape/time/dto/response/TimeResponse.java
- src/main/java/roomescape/time/repository/TimeRepository.java
- src/main/java/roomescape/time/service/TimeService.java
- src/main/resources/schema.sql
- src/test/java/roomescape/RoomescapeControllerTest.java
코드 리뷰 잘 부탁드립니다! 😄
- 시간 관리 기능 추가 
- 시간 추가API
- 시간 조회 API
- 시간 삭제 API 
- 기존 코드 수정 
- Reservation에서 Time 반영하기 
- 계층화 리팩토링
> [Spring Core] 쏘(박소현) 미션 제출합니다.

- src/main/java/roomescape/HomeController.java
- src/main/java/roomescape/reservation/Reservation.java
- src/main/java/roomescape/reservation/ReservationController.java
- src/main/java/roomescape/reservation/ReservationRepositoryJdbc.java
- src/main/java/roomescape/reservation/ReservationService.java
- src/main/java/roomescape/reservation/dto/ReservationRequest.java
- src/main/java/roomescape/reservation/dto/ReservationResponse.java
- src/main/java/roomescape/time/Time.java
- src/main/java/roomescape/time/TimeController.java
- src/main/java/roomescape/time/TimeRepositoryJdbc.java
- src/main/java/roomescape/time/TimeService.java
- src/main/java/roomescape/time/dto/TimeRequest.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
드디어 마지막 미션이네요~!
미션 10단계는 `commit message`에도 적어두었는데, 이미 계층화 되어 있어서 수정할 필요가 없어서 생략했습니다!
리뷰 잘 부탁드립니당!
> [Spring Core] 미나(이지민) 미션 제출합니다.

- src/main/java/roomescape/domain/bean/Hello.java
- src/main/java/roomescape/domain/reservation/controller/ReservationController.java
- src/main/java/roomescape/domain/reservation/dao/JdbcReservationRepository.java
- src/main/java/roomescape/domain/reservation/dao/ReservationRepository.java
- src/main/java/roomescape/domain/reservation/dao/SimpleReservationRepository.java
- src/main/java/roomescape/domain/reservation/dto/ReservationDTO.java
- src/main/java/roomescape/domain/reservation/entity/Reservation.java
- src/main/java/roomescape/domain/reservation/mapper/ReservationMapper.java
- src/main/java/roomescape/domain/reservation/service/ReservationService.java
- src/main/java/roomescape/domain/time/controller/TimeController.java
- src/main/java/roomescape/domain/time/dao/JdbcTimeRepository.java
- src/main/java/roomescape/domain/time/dao/TimeRepository.java
- src/main/java/roomescape/domain/time/dto/TimeDTO.java
- src/main/java/roomescape/domain/time/entity/Time.java
- src/main/java/roomescape/domain/time/exception/TimeException.java
- src/main/java/roomescape/domain/time/service/TimeService.java
- src/main/java/roomescape/global/AppConfig.java
- src/main/resources/application.yml
- src/main/resources/schema.sql
- src/test/java/roomescape/LayerTest.java
- src/test/java/roomescape/domain/bean/BeanTest.java
- src/test/java/roomescape/domain/reservation/ReservationControllerTest.java
- src/test/java/roomescape/domain/time/TimeControllerTest.java
- src/test/java/roomescape/helper/TestHelper.java
어제까지였는데 늦어서 죄송합니다..😂
리뷰 많이많이 부탁드립니다~~!!
> [Spring Core] 보름(손현경) 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/domain/reservation/controller/ReservationController.java
- src/main/java/roomescape/domain/reservation/dto/request/ReservationCreateRequestDto.java
- src/main/java/roomescape/domain/reservation/entity/Reservation.java
- src/main/java/roomescape/domain/roomescape/controller/RoomEscapeController.java
- src/main/java/roomescape/exception/ErrorCode.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/java/roomescape/exception/custom/BusinessException.java
- src/main/java/roomescape/exception/dto/ErrorResponse.java
- src/test/java/roomescape/MissionStepTest.java
안녕하세요. 첫 번째 미션 제출입니다.
리뷰 잘 부탁드립니다 !
- 예약 생성 기능에서 데이터를 전송할 때 관심사의 분리와 데이터 검증을 위해 dto로 구현했습니다.
그리고 record가 getter를 자동으로 생성하고 필드가 불변 타입이라 dto에 적합하다고 생각하는데 어떻게 생각하시는지 궁금합니다.
- 예약 생성 기능에서 `@NotBlank` validator로 `null`, `""`, `" "`를 모두 예외 처리하도록 구현했습니다.
- 예외가 발생하면 `ResponseEntity<ErrorResponse>`로 에러 코드와 에러 메시지를 응답하도록 구현했습니다.
해당 예외 처리 응답에 대해 어떻게 생각하시는지 혹은 더 좋은 의견이 있다면 남겨주세요 !
> [Spring MVC] 김도형 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/controller/ExceptionController.java
- src/main/java/roomescape/controller/PageController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/exception/BadRequestReservationException.java
- src/main/java/roomescape/exception/NotFoundReservationException.java
- src/main/java/roomescape/exception/ReservationExceptionHandler.java
- src/test/java/roomescape/MissionStepTest.java
첫번째 미션 제출합니다.
학습 테스트 페이지 중 예외처리 부분이 누락되어 혼자 공부하며 애매한 부분이 있었는데, 
아래 질문에 대해 의견 남겨주시면 감사하겠습니다!
* `ControllerAdvice`를 통해 예외처리를 해둔 상황입니다. 이때 `controller/ExceptionController`의 네이밍이 적절한지,아니면 `exception/ExceptionHandler`라는 이름으로 따로 빼는게 나을지 모르겠습니다. (Spring docs에서 명시된 내용을 따로 못찾았습니다.)
* 4단계 미션 페이지에 명시된걸 보면 Delete 요청이 들어왔을때 삭제할 예약이 없는 경우, 404(NotFound)가 아닌 400(badRequest)를 날리게 됩니다. 테스트 코드에 맞추기 위해 BadRequest로 처리했지만 개인적으로 NotFound가 더 적합하다 생각하는데, 리뷰어 분께서는 BadRequest, NotFound중 어떤 에러가 더 적합하다고 생각하시는지 의견을 여쭙고 싶습니다.
```java
// === TEST ===
// 삭제할 예약이 없는 경우
RestAssured.given().log().all()
.when().delete("/reservations/1")
.then().log().all()
.statusCode(400);
// === EXCEPTION ===
@ExceptionHandler(NotFoundReservationException.class)
public ResponseEntity handleException(NotFoundReservationException e) { …
```
> [Spring MVC] 이창민 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/controller/HomeController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/dto/reservation/ReservationRequest.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/java/roomescape/exception/InvalidReservationException.java
- src/main/java/roomescape/exception/ReservationNotFoundException.java
- src/test/java/roomescape/MissionStepTest.java
아직 미흡한 부분이 많이 보이는것 같습니다!
뭐든지 좋으니 개선해야할 부분이 보이면 말씀해주시면 감사하겠습니다.
첫 미션 다들 수고하셨습니다
> [Spring MVC] 박정언 미션 제출합니다.

- build.gradle
- src/main/java/cholog/Member.java
- src/main/java/cholog/MemberController.java
- src/main/java/cholog/Person.java
- src/main/java/cholog/SpringMvcApplication.java
- src/main/java/hello/DemoApplication.java
- src/main/java/hello/Greeter.java
- src/main/java/hello/Greeting.java
- src/main/java/hello/GreetingController.java
- src/main/java/roomescape/Controller/ReservationController.java
- src/main/java/roomescape/Controller/RoomescapeController.java
- src/main/java/roomescape/Exception/NotFindReservationException.java
- src/main/java/roomescape/Reservation.java
- src/main/resources/static/hello.html
- src/main/resources/static/hi.html
- src/main/resources/static/index.html
- src/main/resources/templates/hello.html
- src/main/resources/templates/static.html
- src/test/java/cholog/CRUDTest.java
- src/test/java/cholog/ResponseJsonTest.java
- src/test/java/cholog/ResponseStaticTest.java
- src/test/java/cholog/ResponseTemplatesTest.java
- src/test/java/roomescape/MissionStepTest.java
첫미션이라 많이 부족하지만 열심히 해봤습니다.
오류도 잡고 코드도 짜보며 많은 것을 배웠습니다.
> [Spring MVC] 고서현 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/controller/HomeController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/exception/InvalidReservationException.java
- src/main/java/roomescape/exception/NotFoundReservationException.java
- src/main/java/roomescape/model/Reservation.java
- src/test/java/roomescape/MissionStepTest.java
안녕하세요! 개인 사정도 있었는데, 스프링이 처음인지라 많이 어려워 학습이 늦어지는 바람에 예정보다 더 늦었네요... 죄송합니다.
리뷰 잘 부탁드립니다!
중간 중간 커밋하지 않고, 한 번에 커밋을 했는데 다음 번에는 보기 편하도록 나눠서 커밋하겠습니다.
3번, 4번 단계였던 추가, 삭제, 그리고 예외 처리에 대한 개념 숙지가 많이 미흡한 상태에서 작성한 것이라 제가 잘 작성한 것이 맞는지, 개선할 곳이 있는지 살펴봐주시면 감사하겠습니다..!
> [Spring MVC] 함성준 미션 제출합니다.

- .gitignore
- build.gradle
- src/main/java/roomescape/NotFoundReservationException.java
- src/main/java/roomescape/Reservation.java
- src/main/java/roomescape/ReservationController.java
- src/main/java/roomescape/ReservationQueryingDAO.java
- src/main/java/roomescape/ReservationUpdatingDAO.java
- src/main/java/roomescape/RoomescapeController.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
이전 코드와 학습테스트의 예제 코드를 바탕으로 작성했습니다. OOP나 클린코드 관련해서도 피드백 주실 부분이 있으시면 많은 피드백 부탁드립니다.
* h2 DB (in memory db 형태로도 사용가능)
* application.properties에 DB관련 설정하기(콘솔활성화, 콘솔과 디비 url 설정)
* Spring의 JDBC가 추상화된 부분과 JdbcTemplate 사용법
* ResponseEntity.ok().body()로 데이터를 전달하는 법
* keyHolder로 업데이트 된 entity의 PK값 가져오기
* rowMapper
* 이전 단계의 코드들은 필요하지 않을 경우 변경하지 않음
* ReservationUpdatingDAO와 ReservationQueryingDAO클래스를 만들고 JdbcTemplate객체를 생성자의 인자로 받음\
* SELECT처리 시 ReservationQueryingDAO에서 RowMapper를 사용
* INSERT처리 시 ReservationUpdatingDAO에서 KeyHolder를 사용
* ReservationController애서 List 대신 ReservationUpdatingDAO와 ReservationQueryingDAO를 사용
* QueryingDAO, UpdatingDAO객체를 제가 짠 코드처럼 사용하는 것이 아니라 싱글톤패턴을 사용하는 것이 더 올바른 방식인지 궁금합니다. 
* 이전 단계의 코드들을 주석으로 남겨두는 것과 지우는 것 중 어느 쪽이 좋을지 궁금합니다.
* 학습테스트 코드에서 JdbcTemplate의 update메소드를 사용할 때 …
> [Spring JDBC] 김동우 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/dto/ReservationRequest.java
- src/main/java/roomescape/domain/InMemoryReservations.java
- src/main/java/roomescape/domain/JdbcReservations.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/domain/Reservations.java
- src/main/java/roomescape/exception/ExceptionResponse.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
- src/test/java/roomescape/domain/InMemoryReservationsTest.java
- src/test/java/roomescape/support/DatabaseCleaner.java
- src/test/java/roomescape/support/DatabaseCleanerExtension.java
안녕하세요 창민님 만나서 반갑습니다 🙇🏻
궁금한 부분이 있으면 편하게 질문주세요!
> [Spring JDBC] 박성철 미션 제출합니다

- build.gradle
- src/main/java/roomescape/domain/reservation/controller/ReservationController.java
- src/main/java/roomescape/domain/reservation/repository/ReservationDao.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
안녕하세요. JDBC 미션 제출입니다.
리뷰 잘 부탁드립니다. 😊 
같이 논의해 볼 사항이나 질문이 있다면 편하게 남겨주세요 !
> [Spring JDBC] 김도형 미션 제출합니다.

- build.gradle
- src/main/java/hello/Customer.java
- src/main/java/hello/QueryingDAO.java
- src/main/java/hello/SpringJdbcApplication.java
- src/main/java/hello/UpdatingDAO.java
- src/main/java/roomescape/controller/HomeController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/domain/ReservationRepository.java
- src/main/java/roomescape/dto/ReservationDto.java
- src/main/java/roomescape/exception/NotFindReservationException.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/hello/QueryingDaoTest.java
- src/test/java/hello/UpdatingDaoTest.java
- src/test/java/roomescape/MissionStepTest.java
> [Spring JDBC] 고서현 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/common/exception/ErrorCode.java
- src/main/java/roomescape/common/exception/GlobalRestControllerAdvice.java
- src/main/java/roomescape/common/exception/ReservationErrorCode.java
- src/main/java/roomescape/common/exception/ReservationException.java
- src/main/java/roomescape/controller/AdminController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/data/dto/ReservationRequest.java
- src/main/java/roomescape/data/dto/ReservationResponse.java
- src/main/java/roomescape/data/entity/Reservation.java
- src/main/java/roomescape/data/service/ReservationService.java
- src/test/java/roomescape/MissionStepTest.java
비즈니스 로직과 관련된 부분은 Service레이어에서 따로 처리하여 Controller의 책임 분리가 확실하게 되도록 하였습니다.
Exception은 CustomException을 사용하였으며, ControllerAdcvice를 통해 WAS까지 예외가 전달되지 않는다는 것이 좋다고 생각했습니다.
> [Spring MVC] 한석진 미션 제출합니다.

- src/main/java/roomescape/domain/reservation/controller/ReservationController.java
- src/main/java/roomescape/domain/reservation/dto/request/ReservationCreateRequestDto.java
- src/main/java/roomescape/domain/reservation/entity/Reservation.java
- src/main/java/roomescape/domain/reservation/repository/ReservationDao.java
- src/main/java/roomescape/domain/reservation/service/ReservationService.java
- src/main/java/roomescape/domain/roomescape/controller/RoomEscapeController.java
- src/main/java/roomescape/domain/time/controller/TimeController.java
- src/main/java/roomescape/domain/time/dto/request/TimeCreateRequestDto.java
- src/main/java/roomescape/domain/time/entity/Time.java
- src/main/java/roomescape/domain/time/repository/TimeDao.java
- src/main/java/roomescape/domain/time/service/TimeService.java
- src/main/java/roomescape/exception/ErrorCode.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
안녕하세요. Core 미션 제출입니다.
리뷰 잘 부탁드립니다. 😊
같이 논의해 볼 사항이나 질문이 있다면 편하게 남겨주세요 !
> [Spring Core] 김도형 미션 제출합니다.

- build.gradle
- src/main/java/roomescape/ReservationDAO.java
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
학습테스트를 많이 참고해서 코드를 작성해보았습니다..!
일단 controller에 기능을 구현했는데, DAO를 따로 분리하여 사용하도록 수정해보려고 합니다!
> [Spring JDBC] 김보배 미션 제출합니다. 

- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/TimeController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/domain/Time.java
- src/main/java/roomescape/dto/reservation/ReservationRequest.java
- src/main/java/roomescape/dto/time/TimeRequest.java
- src/main/java/roomescape/exception/InvalidTimeException.java
- src/main/java/roomescape/exception/TimeNotFoundException.java
- src/main/java/roomescape/repository/ReservationDao.java
- src/main/java/roomescape/repository/TimeDao.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
안녕하세요 동흠님! 부족한 점이나 의논할 부분 있으시면 편하게 말씀해주세요 ! 앗 그리고 코드 다 짜고 테스트코드까지는 잘 돌아가는데 메인 페이지에서  예약 추가가 갑자기 안되네요 ㅠㅠㅠ 이 부분은 내일까지 제가 코드 수정한 다음 푸시하고 dm으로 말씀드리겠습니다!! 코드 수정 빠르게 하고 푸시할테니 이후에 리뷰해주시면 감사하겠습니다~~!!
> [Spring Core] 박정언 미션 제출합니다

- build.gradle
- src/main/java/roomescape/controller/ControllerExceptionHandler.java
- src/main/java/roomescape/controller/HomeController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/dto/ReservationDto.java
- src/main/java/roomescape/entity/Reservation.java
- src/main/java/roomescape/exception/NotFoundReservationException.java
- src/main/java/roomescape/repository/ReservationRepository.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/java/roomescape/service/ReservationServiceImpl.java
- src/test/java/roomescape/MissionStepTest.java
mvc패턴에 맞춰서 구현을 해보았습니다.
Automic을 이용해서 데이터의 삽입이 있을때 자동으로 숫자를 올리는 기능을 서비스하고 레파지토리에서 어디에 구현을 할지 애매하네요. 레파지토리에 구현하면 id를 setter를 이용하여 직접 정의해주어야해서 setter지양원칙에 따라 서비스에서 생성자에 한꺼번에 정의해서 구현했는데, 더 좋은 구현방법이 있을까요?
또한 예외처리 클래스 정의의 기준은 어느정도가 적당할지 고민을 해야할것같습니다.
저는 현재 예약데이터가 없을때에 대한 예외 발생 클래스만 정의했는데, 만약 도메인이 수없이 많다면 그 많은 도메인에 대한 데이터조회시 예외 발생 클래스를 다 정의해주어야 할까요?
> [Spring MVC] 김원경 미션 제출합니다

- build.gradle
- src/main/java/roomescape/RoomescapeApplication.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/dto/ReservationDTO.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/resources/templates/index.html
- src/test/java/roomescape/MissionStepTest.java
빈 인자 예외처리를 컨트롤러에서 처리할 방법을 찾다가 도메인에서 처리하도록 코드를 짰습니다
자료에 나온대로 custom exception을 만들어볼 예정입니다!
> [Spring MVC] 허준기 미션 제출합니다

- build.gradle
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/dto/ReservationCreate.java
- src/main/java/roomescape/dao/ReservationDao.java
- src/main/java/roomescape/dao/ReservationDaoImpl.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/exception/GlobalExceptionHandler.java
- src/main/java/roomescape/repository/ReservationRepository.java
- src/main/java/roomescape/repository/ReservationRepositoryImpl.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/java/roomescape/service/ReservationServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
1. DAO와 Repository를 어떤 상황에 사용하면 좋은지 궁금합니다.
2. [Entity, DAO, DTO가 무엇이며 왜 사용할까?](https://velog.io/@ohzzi/Entity-DAO-DTO%EA%B0%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)라는 글을 읽고 DTO와 Domain(Entity Class)가 동일하더라도 DAO와 DB 사이에서만 Entity를 사용하고 나머지는 DTO를 사용하는게 맞을까? 라는 궁금증이 생겼습니다. 의견 부탁드립니다.
3. `@Autowired`가 없어도 작동하던데 이유가 뭔지 궁금합니다.
좀 더 쉽게 생성된 id를 가져오는 방법을 찾아보다가 SimpleJdbcInsert를 알게되어서 적용해보았습니다.
이번 미션을 하면서 JPA가 진짜 편하다는것을 느꼈습니다.
> [Spring JDBC] 박성빈 미션 제출합니다.

- src/main/java/roomescape/domain/reservation/controller/ReservationApiController.java
- src/main/java/roomescape/domain/reservation/dao/ReservationDAO.java
- src/main/java/roomescape/domain/reservation/domain/Reservation.java
- src/main/java/roomescape/domain/reservation/dto/ReservationCreateDTO.java
- src/main/java/roomescape/domain/reservation/dto/ReservationResponseDTO.java
- src/main/java/roomescape/domain/reservation/mapper/ReservationMapper.java
- src/main/java/roomescape/domain/reservation/service/ReservationServiceImpl.java
- src/main/java/roomescape/domain/time/controller/TimeAPIController.java
- src/main/java/roomescape/domain/time/controller/TimePageController.java
- src/main/java/roomescape/domain/time/dao/TimeDAO.java
- src/main/java/roomescape/domain/time/domain/Time.java
- src/main/java/roomescape/domain/time/dto/TimeCreateDTO.java
- src/main/java/roomescape/domain/time/dto/TimeResponseDTO.java
- src/main/java/roomescape/domain/time/mapper/TimeMapper.java
- src/main/java/roomescape/domain/time/service/TimeService.java
- src/main/java/roomescape/domain/time/service/TimeServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
프로젝트를 리팩터링 해보는 과정을 거치면서 확장이 용의하게 코딩하고, 계층적으로 설계하는것의 중요성을 알 수 있는 미션이였습니다.
> [Spring Core] 이현수 미션 제출합니다.

- src/main/java/roomescape/controller/PageViewController.java
- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/TimeController.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/domain/Time.java
- src/main/java/roomescape/dto/ReservationRequestDto.java
- src/main/java/roomescape/dto/ReservationResponseDto.java
- src/main/java/roomescape/repository/JdbcTemplateReservationRepository.java
- src/main/java/roomescape/repository/JdbcTemplateTimeRepository.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/java/roomescape/service/ReservationServiceImpl.java
- src/main/java/roomescape/service/TimeService.java
- src/main/java/roomescape/service/TimeServiceImpl.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
지금까지 했던 것들을 복습의 개념으로 다시 구현해보면서 배운 것들을 정리하고 다시 생각할 수 있던 기회가 되었으며
추가로 join과 관련된 쿼리문은 지금까지 많이 사용할 일이 없었는데 inner join을 사용하며 join과 관련된 쿼리문을 공부하고 써볼 수 있는 과제였던 것 같습니다.
> [Spring Core] 김성재 미션 제출합니다.

- src/main/java/roomescape/controller/ReservationController.java
- src/main/java/roomescape/controller/TimeController.java
- src/main/java/roomescape/controller/WebController.java
- src/main/java/roomescape/dao/ReservationDao.java
- src/main/java/roomescape/dao/TimeDao.java
- src/main/java/roomescape/domain/Reservation.java
- src/main/java/roomescape/domain/Time.java
- src/main/java/roomescape/dto/ReservationRequestDto.java
- src/main/java/roomescape/dto/ReservationResponseDto.java
- src/main/java/roomescape/dto/TimeRequestDto.java
- src/main/java/roomescape/dto/TimeResponseDto.java
- src/main/java/roomescape/service/ReservationService.java
- src/main/java/roomescape/service/TimeService.java
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
이 프로젝트에서는 1대 1 관계라 따로 구현하지는 않았지만, Service와 ServiceImpl로 따로 나누어 구현하는 방식에 대해 알게 되었습니다.
회고때는 JPA를 사용해 쉽게 구현해서 DB 관리와 Repository에 대한 부분이 빈약했는데, 이번 Core 과정을 통해 쿼리문을 직접적으로 적용하고 JDBC에 대해 더 많이 공부하면서 다양하게 접근할 수 있어서 좋았습니다!
리뷰 부탁드립니다!
> [Spring Core] 황현식 미션 제출합니다.

- README.md
- build.gradle
- src/main/java/roomescape/GlobalExceptionHandler.java
- src/main/java/roomescape/Reservation.java
- src/main/java/roomescape/ReservationController.java
- src/main/java/roomescape/ReservationService.java
- src/main/java/roomescape/ReservationServiceImpl.java
- src/main/java/roomescape/ViewController.java
- src/main/resources/application.properties
- src/main/resources/schema.sql
- src/test/java/roomescape/MissionStepTest.java
안녕하세요!리뷰 잘 부탁드립니다 ~ 이번에는 구조의 어려움이 있던 과제였습니다.
사실 구조를 좀 더 명확하게 진행하고 싶었는데 우선 제대로 테스트라도 통과하자는 것을 목표로 진행해서 코드에 대한 구조적 변화가 필요한 상태입니다.
Week2  Spring JDBC 5단계 6단계 7단계 완료 했습니다
다만, 코드 정리 및 service class나 repository 등 코드를 좀 더 구조화해서 바꿔야 할 것 같습니다 
현재 상태는 controller에다가 코드가 잔뜩 들어있는 상황인데 이렇게 될 경우 수정에도 용이하지 않고 가독성도 떨어져서 좋은 코드가 아닌 것 같습니다.  아직 스프링의 구조들을 배우고 있지만 이렇게 새로운 문제를 만났을 때 활용하는 것이 좀 부족한 것 같습니다. 이와 관련된 조언이 있다면 주시면 감사하겠습니다.
> {Spring JDBC] 김수현 미션제출합니다
